spring.application.name=demo
management.endpoints.web.exposure.include= *
management.info.env.enabled=true
info.app.name= SpringFirst
info.app.description= first spring boot project
info.app.version= 1.0.0
#management.endpoints.web.exposure.exclude= health,info
tester.name= Ayman
framework.name=JUnit
server.port=7070
server.servlet.context-path=/demo01


